name: "Terraform"

on:
  push:
    branches:
      - main
      - stage
  pull_requests:
    branches:
      - main
      - stage

jobs:

  format_validate_lint:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        terraform-version: [ 1.0 ]
        tflint_version: [ latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: ${{ matrix.tflint_version }}
      
      - name: Terraform init
        id: terraInit
        run: terraform init

      - name: Terraform format
        id: terraFormat
        run: terraform fmt -recursive -no-color -check

      - name: Terraform lint
        id: terraformLint
        run: tflint --init -c .tflint.hcl && tflint -no-color --force

  golng_format_vet:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go_version: [ 1.16.5 ]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Go format
        id: goFormat
        run: go fmt ./...
      
      - name: Go vet
        id: goVet
        run: go vet ./...

  terratests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        terraform_version: [ 1.0 ]
        go_version: [ 1.16.5 ]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run Terratests
        id: runTerratests
        run: cd terratests/ && go test -v -timeout 60m