name: "Terraform"

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
     
  terraform_format_validate:
    name: Format and validate Terraform Code Base
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        terraform-version: [ 1.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}
     
      - name: Terraform init
        id: terraInit
        run: terraform init

      - name: Terraform format
        id: terraFormat
        run: terraform fmt -recursive -no-color -check

  golang_format_vet:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go_version: [ 1.16.5 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Go format
        id: goFormat
        run: go fmt .
        working-directory: ./terratests
      
      - name: Go vet
        id: goVet
        run: go vet .
        working-directory: ./terratests

  terratests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        terraform_version: [ 1.0 ]
        go_version: [ 1.16.5 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: test
        run: terraform --version

      - name: Run Terratests
        id: runTerratests
        run: go test -v -timeout 60m
        working-directory: ./terratests